# Basic action information
name: 'Setup Yarn (version berry)'
description: 'An GitHub Action to set up a Yarn environment with version berry.'
author: 'crrashh1542'
branding:
   icon: 'package'
   color: 'blue'

# Parameter to input
inputs:
   fetch-depth:
      description: 'The depth to checkout the source of your repo'
      default: '0'
   node-version:
      description: 'The version of Node.js to be set up'
      default: '20'

# Detailed work to do
runs:
   using: 'composite'
   steps:
    - name: 🧐 Checkout
      uses: actions/checkout@v4
      with:
         fetch-depth: ${{ inputs.fetch-depth }}

    - name: 🔧 Setup Node.js
      uses: actions/setup-node@v4
      with:
         node-version: ${{ inputs.node-version }}
         cache: 'yarn'

    - name: 🛠️ Setup environment
      shell: bash
      run: |
         yarn set version berry
         yarn install
